import esbuild from "esbuild";
import process from "process";
import { builtinModules } from "node:module";
import { readFileSync } from "node:fs";

// pdf.js normally loads its worker from a separate file by URL at runtime.
// That file can't ship alongside main.js: Obsidian's community-plugin
// installer only ever downloads main.js/manifest.json/styles.css from a
// release, so a 4th asset 404s for every real user. Embedding the worker
// source as a string and building a Blob URL at runtime (see pdf.ts) avoids
// needing a second file at all.
const workerSource = readFileSync("node_modules/pdfjs-dist/build/pdf.worker.min.mjs", "utf8");

// Same story for tesseract.js, which otherwise pulls its worker script off a
// CDN at runtime.
const tesseractWorkerSource = readFileSync("node_modules/tesseract.js/dist/worker.min.js", "utf8");

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === "production";

const context = await esbuild.context({
  banner: { js: banner },
  entryPoints: ["src/main.ts"],
  bundle: true,
  external: [
    "obsidian",
    "electron",
    "@codemirror/autocomplete",
    "@codemirror/collab",
    "@codemirror/commands",
    "@codemirror/language",
    "@codemirror/lint",
    "@codemirror/search",
    "@codemirror/state",
    "@codemirror/view",
    "@lezer/common",
    "@lezer/highlight",
    "@lezer/lr",
    ...builtinModules,
  ],
  format: "cjs",
  target: "es2018",
  logLevel: "info",
  sourcemap: prod ? false : "inline",
  treeShaking: true,
  outfile: "main.js",
  define: {
    __PDF_WORKER_SOURCE__: JSON.stringify(workerSource),
    __TESSERACT_WORKER_SOURCE__: JSON.stringify(tesseractWorkerSource),
  },
});

if (prod) {
  await context.rebuild();
  process.exit(0);
} else {
  await context.watch();
}
